### ISSUE TITLE
ModuleNotFoundError: No module named 'ClusterEnsembles'

### ISSUE THREAD

**Issue by Djenerly** [phineasng/DECODE#4]
I'm using Jupyter notebook and I keep getting this error even though I already installed all packages. When I try to import cluster ensemble as CE as well, it says 'zsh: command not found: import'. Import works just fine when it's being used for pandas and numpy, etc. Has anyone else found a solution to these issues? I've tried almost everything I've seen so far. Thanks!

**Comment by phineasng** [comment]
Hey. Unfortunately it looks like ClusterEnsembles is not downloadable/installable anymore. 

Our quick and dirty solution was just to remove the dependency since the tutorials were not using cluster ensembling (see issue #1 and PR #2 ). 

If you don't need to do cluster ensembling for the time being, you can just pull the latest version of the code. There should be no dependency on ClusterEnsembles anymore.

If you need to do cluster ensembling, give us a couple of days and we will try to find an alternative. Or feel free to suggest/implement an alternative :)

**Comment by Djenerly** [comment]
> Hey. Unfortunately it looks like ClusterEnsembles is not downloadable/installable anymore.
> 
> Our quick and dirty solution was just to remove the dependency since the tutorials were not using cluster ensembling (see issue #1 and PR #2 ).
> 
> If you don't need to do cluster ensembling for the time being, you can just pull the latest version of the code. There should be no dependency on ClusterEnsembles anymore.
> 
> If you need to do cluster ensembling, give us a couple of days and we will try to find an alternative. Or feel free to suggest/implement an alternative :)

**Comment by Djenerly** [comment]
Thanks!
